### ISSUE TITLE
The second page's first table row does not keep the height if you set height with a value.

### ISSUE THREAD

**Issue by xiangrui-zeng** [bpampuch/pdfmake#1369]
the first row is higher than others rows.
No. 22
```
// playground requires you to assign document definition to a variable called dd

var dd = {
	content: [
				'With same height:',
		{
			style: 'tableExample',
			table: {
				heights: 30,
				body: [
					['row 1', 'column B'],
					['row 2', 'column B'],
					['row 3', 'column B'],
					['row 4', 'column B'],
					['row 5', 'column B'],
					['row 6', 'column B'],
					['row 7', 'column B'],
					['row 8', 'column B'],
					['row 9', 'column B'],
					['row 10', 'column B'],
					['row 11', 'column B'],
					['row 12', 'column B'],
					['row 13', 'column B'],
					['row 14', 'column B'],
					['row 15', 'column B'],
					['row 16', 'column B'],
					['row 17', 'column B'],
					['row 18', 'column B'],
					['row 19', 'column B'],
					['row 20', 'column B'],
					['row 21', 'column B'],
					['row 22', 'column B'],
					['row 23', 'column B'],
					['row 24', 'column B'],
					['row 25', 'column B'],
					['row 26', 'column B'],
					['row 27', 'column B'],
					['row 28', 'column B'],
					['row 29', 'column B'],
					['row 30', 'column B'],
				]
			}
		}
	]
	
}
```
![image](https://user-images.githubusercontent.com/5535180/39919538-e1e0aab4-554e-11e8-9a72-b190314145a0.png)

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/f80ab4a4433cd638a83d48881edf59a3873511d4.

**Comment by suknic** [comment]
This bug is still present in 0.1.54  

The first (non header) row of a table that flowed over to the next page that has a height given (either through "heights": {number} or "heights": {array} will have double the specified size.  

Minimalistic test case: 
    var dd = {
    	content: [
            {
                "margin": [
                    0,
                    740,
                    0,
                    0
                ],
                "table": {
                    "heights": 12,
                    "body": [
                        [
                            'Lorem ipsum',
                            'Lorem ipsum'
                        ],
                        [
                            'Lorem ipsum',
                            'Lorem ipsum'
                        ]
                    ]
                }
            }
    	]
    }

**Comment by emir-gradient** [comment]
It seems that using 'dontBreakRows' attribute (with value 'true') on "table" neutralizes this bug.
