### ISSUE TITLE
SVG patterns do not render when using minified version of pdfmake

### ISSUE THREAD

**Issue by jpsilva** [bpampuch/pdfmake#1832]
Using patterns in SVG works as expected when importing the unminified version of pdfmake (pdfmake/build/pdfmake.js). But they render as solid black when either importing pdfmake.min.js or minimizing the original with Angular. I haven't noticed any other discrepancies between

Result with unminified version:
![image](https://user-images.githubusercontent.com/422263/67484211-954c0e80-f635-11e9-8361-e32811639fc2.png)

Result with minified version:
![image](https://user-images.githubusercontent.com/422263/67484246-a85ede80-f635-11e9-8641-cd86767e8a44.png)

Code used to generate both results:
```javascript
const pdfDoc = {
  content: [
    {
      svg: `
        <svg id="svg" viewBox="0 0 600 600">
          <defs>
            <pattern id="stripes" width="30" height="30" patternUnits="userSpaceOnUse">
              <path d="M0,0 15,0 0,15 z" fill="#00cc66" />
              <path d="M0,30 30,0 30,15 15,30 z" fill="#00cc66" />
            </pattern>
          </defs>
          <rect x="0" y="0" width="400" height="400" fill="#0044ff" />
          <rect x="200" y="200" width="400" height="400" fill="url(#stripes)" />
        </svg>
      `,
      width: 200
    }
  ]
};
const pdf = pdfMake.createPdf(pdfDoc);

pdf.open();
```

**Comment by matroskin** [comment]
@jpsilva managed to solve the problem?

**Comment by hielfx** [comment]
I'm also facing this issue with v0.1.68

**Comment by ThePongBRIKL** [comment]
Hi, i also got this issue when working on client side. any update soon ?

**Comment by QuentinJanuel** [comment]
Hello, I have this issue as well.
Anyone knows how can I at least force the unminified version on ReactJS production mode?
I hope the bug will be fixed in a near future : )

**Comment by ThePongBRIKL** [comment]
Hi guy, good news, i just solve this issue !!.
So the issue it come from svg-to-pdfkit dependencies not from pdfmake.

The main issue is constructor of "PDFPattern()" turn it self to "Object" after build.
Then it make this condition away false "`if (color[0].constructor.name === 'PDFPattern')`"
About line 163 and 171
So that why it not assign your pattern.

How to fix it up to you for me i add more parameter to check it is pattern fill or not.
See my attach below.

If you dont know where then follow this suggestion
- Copy my source.js 
- Then paste it to node_modules/svg-to-pdfkit/source.js
- Then run build
- That's it !!

my edit source.js
https://filebin.net/f6ja3bo4pmqqpglz/source.js?t=cnlux7mq

Screenshot - also work well with image pattern.
https://filebin.net/4838bdcuiee8eon1/Screenshot_2020-12-09_143730.jpg?t=lcnl1036


Sorry for my bad English. 
Thank you, enjoy hacking everyone.

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/27d4b1c0646d888f78c94ffe37aea1981427a999 (in 0.1 branch) and https://github.com/bpampuch/pdfmake/commit/8ce24e068dc636511871c38bd97b99c3ecf412b7 (in master)

**Comment by yagoar** [comment]
Hi, we're still getting this issue on version 0.1.70
After building the app for production with create-react-app, the SVG pattern is shown as a solid black box. 

Development build result:
![Bildschirmfoto 2021-02-01 um 12 03 20](https://user-images.githubusercontent.com/9568404/106450458-83d2f280-6485-11eb-8579-816de3767b63.png)

Production build result:
![Bildschirmfoto 2021-02-01 um 12 03 27](https://user-images.githubusercontent.com/9568404/106450468-86354c80-6485-11eb-887b-2b02b9b166a1.png)

**Comment by rafaeelneto** [comment]
im getting the same issue with version 0.2.4

**Comment by liborm85** [comment]
Tested with 0.2.4 and works correctly.

**Comment by rafaeelneto** [comment]
after install the pdfmake you can change the pdfmake.js build file and change around the line 23032 that has 
```
function docFillColor(color) {
    if (color[0].constructor.name === 'PDFPattern') {
      doc.fillOpacity(color[1]);
      docUsePattern(color[0], false);
    } else {
      doc.fillColor(color[0], color[1]);
    }
  }
function docStrokeColor(color) {
    if (color[0].constructor.name === 'PDFPattern') {
      doc.strokeOpacity(color[1]);
      docUsePattern(color[0], true);
    } else {
      doc.strokeColor(color[0], color[1]);
    }
  }
```

and add another condition to both if blocks
```
function docFillColor(color) {
    if (color[0].constructor.name === 'PDFPattern' || color[0].dx) {
      doc.fillOpacity(color[1]);
      docUsePattern(color[0], false);
    } else {
      doc.fillColor(color[0], color[1]);
    }
  }

  function docStrokeColor(color) {
    if (color[0].constructor.name === 'PDFPattern' || color[0].dx) {
      doc.strokeOpacity(color[1]);
      docUsePattern(color[0], true);
    } else {
      doc.strokeColor(color[0], color[1]);
    }
  }
```
if you're using something like github actions you can copy that modified pdfmake.js file into your project folder and run the following command after run npm install on cloud
`npm ci && cp <your-pdfmake-folder>/pdfmakeCustom.js node_modules/pdfmake/build/pdfmake.js`

**Comment by liborm85** [comment]
Re-tested with 0.2.5 and works correctly.

**Comment by mickey58github** [comment]
I get exactly the same problem when creating PDFs that contain pattern fills on Heroku Cloud with PDFsave. This is a big issue for our app. I'm using PDFSave v0.2.5. Is the above fix contained in v0.2.5 or not?

**Comment by MoosArga** [comment]
I get the same issue with 0.2.7. The fix on svg-to-pdfkit suggested by [ThePongBRIKL](https://github.com/ThePongBRIKL) solves the issue. 
Any other option to avoid that kind of solutions ? I'm not a big fan to have to change my dependencies sources to get things work.

**Comment by LeGoffMael** [comment]
I also encountered this issue today while using the latest version `0.2.9`.
I am using Vite in my project and the issue seems the be coming from vite's build minification.

I fixes it by adding those lines to the `vite.config.ts` (which basically reproduce https://github.com/bpampuch/pdfmake/commit/8ce24e068dc636511871c38bd97b99c3ecf412b7) :
```ts
build: {
    minify: 'terser',
    terserOptions: {
      keep_classnames: true,
      keep_fnames: true
    }
  },
```
another solution is simply to disable the minification
```ts
build: { minify: false },
```

**Comment by kfmadhusudhanj** [comment]
As @rafaeelneto mentioned in his comment we can do same code changes 
```
function docFillColor(color) {
    if (color[0].constructor.name === 'PDFPattern' || color[0].dx) {
      doc.fillOpacity(color[1]);
      docUsePattern(color[0], false);
    } else {
      doc.fillColor(color[0], color[1]);
    }
  }

  function docStrokeColor(color) {
    if (color[0].constructor.name === 'PDFPattern' || color[0].dx) {
      doc.strokeOpacity(color[1]);
      docUsePattern(color[0], true);
    } else {
      doc.strokeColor(color[0], color[1]);
    }
  }
```

To execute this we can use npm hooks in **`package.json`**

```
 "scripts": {
    "postinstall": "cp <your-pdfmake-folder>/pdfmakeCustom.js node_modules/pdfmake/build/pdfmake.js 
 }

```
