### ISSUE TITLE
Footer not working after upgrading to 1.17

### ISSUE THREAD

**Issue by mikend** [bpampuch/pdfmake#262]
I upgraded to 1.17 and my footer does not appear anymore.

The example below renders no header or footer in the playground:

    var dd = {
      header: 'simple text',
      footer: {
        columns: [
          'Left part',
           { text: 'Right part', alignment: 'right' }
        ]
      },
      content: 'Content'
    };

**Comment by jthoenes** [comment]
Hi, this is a duplicate of #227 - which has already been fixed but the fix has not been released yet.

**Comment by bpampuch** [comment]
Done, 0.1.18 is out now

We're using webpack instead of browserify now so it should be easier to make custom builds

In order to build pdfmake, simply type: ```gulp``` or ```gulp build```

**Comment by git-back-end** [comment]
Can anyone help me? The footer still doesn't appear, but header does

**Comment by git-front-end** [comment]
Please can someone help me, it still didn't work
