### ISSUE TITLE
"Uncaught RangeError: Source is too large" in Chrome dev build (60.0.3100.0)

### ISSUE THREAD

**Issue by CodingGorilla** [bpampuch/pdfmake#998]
So I know this is a dev build of chrome and not necessarily a final product (so this issue might go away), but we had a customer actually run into this today and I want to try to get out in front of it if this is going to be a problem when Chrome 60 is actually released.

Here's the stack trace:

```
pdfmake.js:24651 Uncaught RangeError: Source is too large
    at Uint8Array.set (native)
    at Object.arraySet (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:24651:13)
    at read_buf (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:23024:10)
    at fill_window (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:23239:10)
    at Config.deflate_slow [as func] (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:23558:8)
    at Object.deflate (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:24476:39)
    at Zlib._write (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:22715:34)
    at https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:22658:21
    at Item.run (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:20363:15)
    at drainQueue (https://ui.waterlinkconnect.com/bower_components/pdfmake/build/pdfmake.js:20333:43)
arraySet @ pdfmake.js:24651
read_buf @ pdfmake.js:23024
fill_window @ pdfmake.js:23239
deflate_slow @ pdfmake.js:23558
deflate @ pdfmake.js:24476
Zlib._write @ pdfmake.js:22715
(anonymous) @ pdfmake.js:22658
Item.run @ pdfmake.js:20363
drainQueue @ pdfmake.js:20333
setTimeout (async)
process.nextTick @ pdfmake.js:20353
maybeReadMore @ pdfmake.js:19811
readableAddChunk @ pdfmake.js:19550
Readable.push @ pdfmake.js:19503
PDFDocument._write @ pdfmake.js:18764
PDFDocument @ pdfmake.js:18677
PdfPrinter.createPdfKitDocument @ pdfmake.js:2101
Document._createDoc @ pdfmake.js:82
Document.getBase64 @ pdfmake.js:170
initiateReportGeneration @ generateReportService.js:859
(anonymous) @ generateReportService.js:18
processQueue @ angular.js:14634
(anonymous) @ angular.js:14650
$eval @ angular.js:15916
$digest @ angular.js:15727
(anonymous) @ angular.js:15955
completeOutstandingRequest @ angular.js:5490
(anonymous) @ angular.js:5762
setTimeout (async)
Browser.self.defer @ angular.js:5760
$evalAsync @ angular.js:15953
(anonymous) @ angular.js:14535
scheduleProcessQueue @ angular.js:14650
$$resolve @ angular.js:14687
resolve @ angular.js:14670
(anonymous) @ angular.js:14619
img.onload @ generateReportService.js:87
```

And a screenshot of the source where the error occurs:

![pdfmake1](https://cloud.githubusercontent.com/assets/570801/26162085/bc393e50-3af3-11e7-89cc-0488c0c5b6a4.png)

I can tell you that in Chrome 58 (production) this same code works just fine.  Let me know if there's any additional information I can provide.

**Comment by JohhnyP** [comment]
I can confirm this happens in Version 61.0.3141.7 (Official Build) dev (64-bit) also.
On version <=59 works fine.

Uncaught RangeError: Source is too large
    at Uint8Array.set (native)
    at Object.arraySet

**Comment by liborm85** [comment]
Tested on final version 60.0.3112.78 (64bit) and all works fine.

**Comment by skylize** [comment]
I have this issue in 60.0.3112.90. Attempted running my app in portable version of 60.0.3112.78, based on comment from @liborm85. Still received error. Tried again in 59.0.3071.115 as per comment by @JohhnyP and the error went away. 

So, as stated by JohhnyP, this is an existing problem with 60+ versions of Chrome. This issue should not be marked closed.

I'll try to work on creating a minimal case for this if I can, but my pdfmake code is running in an iframe created by a Chrome extension, using data generated outside the frame, so it's a little difficult to isolate.

**Comment by skylize** [comment]
Hmm. Maybe this can stay closed after all. It seems to be a browserify bug that was fixed. Problem went away for me after upgrading to browserify v14.4.0.

**Comment by CodingGorilla** [comment]
@skylize We recently had a customer report this bug to us.  They were using the latest stable version of Chrome (60.something).  We are unable to reproduce it with the same versions ourselves, though.  We do not use browserify at all in our application.

So far we have not been able to figure out why this is happening on this one specific machine and no others (that we know of).  Any ideas on what to look at?

**Comment by skylize** [comment]
@CodingGorilla I haven't looked at the code for my project for a while. When I came back to it because of this issue, I thought I was using pdfmake because of many artifacts I did not delete from a pdfmake version of the app. But it turns out I actually used pdfkit. which is the upstream project pdfmake was built on.

If you have browserify in you build process, you should update it. That fixed the problem for me. If you still have the bug, you should report it upstream here [devongovett/pdfkit](https://github.com/devongovett/pdfkit).

**Comment by thumptech** [comment]
I am having the same problem.  It seems to be a problem with the length of the dataurls I'm using to embed images.  If I make them uselessly small, it works ok.

**Comment by liborm85** [comment]
Tested with Chrome version 60.0.3112.78 and 60.0.3112.90 and with pdfmake 0.1.32 and 0.1.31. Download, open and print works ok always.

**Comment by CodingGorilla** [comment]
Testing now with Chrome 61.0.3163.25 we are consistently getting this error whenever a PNG image is used.

**Comment by CodingGorilla** [comment]
Ok, this is resolved when I updated to the latest release of pdfMake.

**Comment by Prahadeesh92** [comment]
I updated pdfmake to the latest version 0.1.32.  My Chrome version is 60.0.3112.101. When I am trying to print, I am getting the same error "Uncaught RangeError: Source is too large".

**Comment by JohhnyP** [comment]
Problem still persists with Chrome Version 61.0.3163.49 (Official Build) beta (64-bit)
Also in http://pdfmake.org/playground.html#  Print and Open do nothing.
